name: Deploy

on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: up9cloud/action-rsync@v1.4
        env:
          HOST: ${{secrets.DEPLOY_HOST}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: ${{secrets.DEPLOY_TARGET}}
          MODE: push
          VERBOSE: true
          PORT: ${{secrets.DEPLOY_PORT}}
          USER: ${{secrets.DEPLOY_USER}}
          ARGS: -avz --exclude-from=.gitignore --exclude=/.git/ --exclude=/.github/
